apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: synergychat-api
  ports:
    - protocol: TCP
      port: 80 # The port exposed on the service (optional but usually needed)
      targetPort: 8080 # The port your app is listening on inside the container
